import { type NextPage } from "next";
import Head from "next/head";

import f from "@/utils/firebase"

import { api } from "@/utils/api";
import { useEffect } from "react";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  useEffect(() => {
    f.findAll("connection").then((r) => {console.log(r)})

  }, [])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        Hi
      </main>
    </>
  );
};

export default Home;
